# Profile section
profile:
  first_name: Salvador
  last_name: Hernandez Palencia
  picture: https://picture.com.jpeg   # Hosted picture
  # picture: static/img/rodo_2021.png  # Local picture
  contact:
    address_one: Guadalajara, Jalisco
    address_two:
    phone: (+52) CONTACT-ME-@!
  email: salvadorhp@live.com
  description: |
    I am an IT Lead passionate and motivated by the evolution and development of new technologies leading software development projects for 20 + years. 
    Demonstrable experience in developing high-performing teams to deliver innovating solutions, leveraging agile frameworks to foster collaborative thinking, 
    continuos improvement, technology and process changes to meet business needs.


# Social section
social:
  website: https://salvadorhernandez.xyz
  github: https://github.com/Shava11/
  linkedin: https://www.linkedin.com/in/salvador-hernandez-b36673b6/
  facebook:
  dev: 
  medium: 


# Experience section
experience:
  item7:
    position: Director of Technology & Community
    company: Gorilla Logic
    from: August 2022
    to: Current
    description: >
      My role is critical for driving Gorilla Logic business growth, manage teams and stablish strong relationships with Community Leads and other key stakeholders in Mexico. I’m responsible for overseeing and managing technology organization, including understanding the company's business goals and strategy, aligning technology strategy and direction to achieve those goals.
    link: https://gorillalogic.com/
  item6:
    position: Delivery Manager
    company: DigitalOnUs by Tech Mahindra 
    from: March 2022
    to: August 2022
    description: >
      My responsabilities for planning and executing projects to ensure successful delivery within defined timelines, budgets, and quality standards. This includes creating project plans, defining project scope and objectives, allocating resources, and monitoring progress. From Team Management and resource allocation to Client Relationship management where some of my responsibilities.
    link: https://www.digitalonus.com/
  item5:
    position: Platform & DevOps Manager
    company: AstraZeneca
    from: September 2018
    to: March 2022
    description: >
      People and Platform Manager, leading Release engineers and Test teams in Guadalajara GTC for the Commercial IT division. Responsible of implementing a Platform Delivery framework within the Business and technology deployment work stream leads, to configure and deploy the different environments for Salesforce and other different platforms, supporting the operation of how Campaigns and Commercialization of Pharma products operate on Health Industry.
  link: http://www.astrazeneca.com
  item4:
    position: Project Delivery Manager
    company: DXC Technology
    from: December 2016
    to: September 2018
    description: >
      Responsible for planning and executing projects to ensure successful delivery within defined timelines, budgets, and quality standards. This includes creating project plans, defining project scope and objectives, allocating resources, and monitoring progress. From Team Management and resource allocation to Client Relationship management where some of my responsibilities.
    link: https://dxc.com/us/en
  item3:
    position: IT Support Specialist
    company: Hewlett-Packard Enterprise
    from: April 2011
    to: December 2016
    description: >
      As an IT Support Specialist, I provided technical support to end-users for HP systems and applications. I was accountable of troubleshooting hardware and software issues, providing solutions to technical problems. System Maintenance and Upgrades by supporting other engineers responsible for applying software updates and patches, monitoring system performance, and performing regular backups including planning and executing system upgrades or migrations. .
    link: http://hpe.com
  item2:
    position: Test Data Analyst
    company: Tata Consultancy Services
    from: October 2009
    to: April 2011
    description: >
      This was a critical role for the client I was assigned to, since it is the military bank in the USA: USAA, and I was in charge of creating and maintaining automated scripts using tools as LoadRunner and Quick Test Pro to generate Test Data for test purposes and avoid filtering production data from systems.
  link: http://www.tcs.com
  item1:
    position: AI Research Assistant
    company: Research Center in Mathematics (CIMAT A.C.)
    from: February 2018
    to: February 2019
    description: >
      On charge of doing research and building neural networks for computer vision problems, focused on applications and solutions for real industry issues. Deployed trained models to production.
  reference: https://rodolfoferro.xyz/resume/


# Education section
education:
  item1:
    institution: Artificial Intelligence CONACYT Consortium – CIMAT A.C.
    program: Winter School on Artificial Intelligence
    description: Attendee to workshops on optimization, deep learning and reinforcement learning. Event organized by the National Consortium on Science and Technology in Mexico.
    from: February 2019
    to: February 2019
  item2:
    institution: University of Guanajuato / CIMAT A.C.
    program: Bachelor of Mathematics
    description: Major in Mathematics with Mathematical Computing as terminal area.
    from: August 2011
    to: July 2018
  item3:
    institution: Harvard University
    program: Summer Internship – Adapting machine learning techniques for chemistry problems.
    description: Worked on a project to calibrate and predict molecular properties using Gaussian processes.
    from: June 2017
    to: August 2017
  reference: https://rodolfoferro.xyz/resume/


# Community section:
community:
  item0:
    institution: Omdena
    program: Community Builder
    description: "Selected as a community builder at Omdena due to exemplary performance in their AI challenge on the tree identification challenge to prevent fire outbursts."
    from: September 2019
    to: Present
    link: https://omdena.com
  item1:
    institution: Future Lab
    program: Co-founder and Coordinator
    description: "Co-founder and coordinator of Future Lab, a community of tech developers for the future. We maily work under three axis: a) Develop awesome tech based projects, b) Share knowledge with the community, and c) Networking with other communities. As a member of Future Lab I have participated on big events such as Talent Land with an AI talk."
    from: April 2017
    to: Present
    link: https://futurelab.mx
  item2:
    institution: GitHub Education
    program: GitHub Campus Experts Program
    description: Mexican member of the GitHub Campus Experts Program, encouraging to empower other student communities. I also serve as a mentor in different events such as Startup Weekends, hackathons, innovation events, etc.
    from: October 2017
    to: Present
    link: https://githubcampus.expert/RodolfoFerro/
  item3:
    institution: Clubes de Ciencia México
    program: Guanajuato Comitee Member and Instructor
    description: Co-organizer of the intensive one-week summer science workshops of Clubes de Ciencia México in Guanajuato. Besides organizing, I have participated teaching science workshops (in particular a physics workshop, based on a Nobel Prize design, and artificial intelligence workshops) for high school and undergrad students.
    from: January 2015
    to: Present
    link: https://www.clubesdeciencia.mx
  item4:
    institution: Google Programs
    program: Google Student Ambassador and GDG
    description: Served as a Google Student Ambassador Latam for the University of Guanajuato, empowering the student community with Googleness and Google technologies to make their life easier. Currently helping the GDG León with tech talks and workshops about AI as a core member of the team. Do cool things that matter.
    from: August 2014
    to: July 2015
    link: https://www.meetup.com/es/GDGLeon/
  reference: https://rodolfoferro.xyz/resume/



# Skills section
tools:
  # Consider that the following are fa icons:
  #   https://fontawesome.com/icons?d=gallery&s=brands
  - jira
  - confluence
  - miro
  - github
  - google
  - google-drive
  - slack
  - trello
  - apple

extra_skills:
  # - Facebook Messenger, Telegram, and SMS bots
  - Web scraping and web automation
  - APIs and web development, MongoDB
  - Image processing and computer vision
  - Machine learning and deep learning
  - Several Python packages – Flask, NumPy, matplotlib, TensorFlow, etc.


# Talks and workshops section
workshops:
  item0:
    event: TEDxUNAMLeón
    workshop: AI in modern times, February 2020.
    material:
    link: https://www.ted.com/tedx/events/35293
  item1:
    event: PyCon Colombia 2020
    workshop: 'Workshop – DLaaS: Building cloud-based intelligent solutions, February 2020.'
    material: https://github.com/RodolfoFerro/PyConCo20
    link: https://www.pycon.co/ponentes/rodolfo-ferro/
  item2:
    event: International Meeting on Artificial Intelligence and its Applications (RIIAA) 2.0.
    workshop: Workshop – Deep Learning as a Service (DLaaS), August 2019.
    material: https://github.com/RodolfoFerro/RIIAA19-DLaaS
    link: https://riiaa.org
  item3:
    event: LAB León Web Dev Crash Course 2019.
    workshop: Crash Course – Introduction to Web Development with Python and Flask, August 2019.
    material: https://github.com/RodolfoFerro/Flask101
    link: https://flask101.glitch.me
  item4:
    event: DevDay León 2019 by Hackademy.
    workshop: Workshop – (AI) API development with Python, August 2019.
    material: https://github.com/RodolfoFerro/PythonBaseAPI
    link:
  item5:
    event: Clubes de Ciencia México 2019.
    workshop: Workshop – Revealing the Hidden Hyperspectrum with Artificial Neurons, July 2019.
    material: https://rodolfoferro.xyz/hyperspectrum/
    link:
  item6:
    event: DevDay Mérida 2019.
    workshop: Workshop – Artificial Intelligence with Python, July 2019.
    material: https://github.com/RodolfoFerro/DevDayMid2019
    link:
  item7:
    event: Talent Land 2019.
    workshop: Talk – A.I. in modern times, April 2019.
    material:
    link: https://jaliscotalentland2019.sched.com/event/MzAs/inteligencia-artificial-en-tiempos-modernos
  item8:
    event: PythonDay México 2018.
    workshop: Talk – Data Science with Python, December 2018.
    material: https://github.com/RodolfoFerro/DataSciPy
    link:
  item9:
    event: PythonDay México 2018.
    workshop: Workshop – Machine Learning as a Service (MLaaS), November 2018.
    material: https://github.com/RodolfoFerro/MLaaS
    link:
  item10:
    event: HERE Hackathon at Technological University of Leon.
    workshop: Mentor on the event. Talk – Integration of Technological Solutions, November 2018.
    material: https://github.com/RodolfoFerro/HereHackathon
    link:
  item11:
    event: 6th. International Conference in Software Engineering Research and Innovation (CONISOFT).
    workshop: Workshop – Introduction to Neural Networks with Keras, October 2018.
    material: https://github.com/RodolfoFerro/CONISOFT2018
    link: http://conisoft.org/2018/public/
  reference: https://rodolfoferro.xyz/resume/


# Projects section
projects:
  item1:
    title: flask-resume-template
    subtitle: A resume template built with Flask
    description: An easy-to-configure simple resume template built with Flask and Bootstrap.
    link: https://flask-resume-template.glitch.me
    github: https://github.com/RodolfoFerro/flask-resume-template/
    img: flask-resume-template.png
    tags: [Flask, Python, Bootstrap]
  item2:
    title: DLaaS
    subtitle: Google Colab Notebooks
    description: A set of Google Colab notebooks and a Flask base API to learn and serve Deep Learning. Prepared for my workshop at RIIAA 2.0.
    link: https://rodolfoferro.xyz/RIIAA19-DLaaS/
    github: https://github.com/RodolfoFerro/RIIAA19-DLaaS
    img: riiaa.png
    tags: [Python, Tensorflow 2.0, Keras, Deep Learning]
  item3:
    title: impipes
    subtitle: Python package
    description: A Python package to build image pipelines in a simple way. Preprocess data to feed neural networks in an easier way.
    link: https://impipes.readthedocs.io/en/latest/
    github: https://github.com/RodolfoFerro/impipes
    img: impipes.png
    tags: [Python, PyPI, Images, Data Preprocessing, Documentation]
  item4:
    title: MNIST Web Classifier
    subtitle: A CNN served as a web platform
    description: Classify handwritten digits directly on your computer or your phone. As simple as taking a picture of a written random multi-digit number.
    link: https://flask-micro-template.glitch.me
    github: https://github.com/RodolfoFerro/flask-micro-template
    img: keras-mnist.png
    tags: [Python, Bootstrap, Web Platform, Flask, MNIST, CNN, Keras]
  item5:
    title: EmojiMerida
    subtitle: Google Colab Notebook
    description: A real-time coding session with an emotion recognizer on facial expressions for a Data Mérida meetup (01/04/2019). The Ai was developed with Python and Keras.
    link: https://colab.research.google.com/github/RodolfoFerro/EmojiMerida/blob/master/Data_M%C3%A9rida.ipynb
    github:
    img: data-merida.png
    tags: [Python, Computer Vision, Keras, Neural Networks]
  item6:
    title: PythonBaseAPI
    subtitle: API template built with Flask
    description: API template built with Python and Flask. Serve an Iris classifier as an API. Content for a workshop.
    link: https://docs.google.com/presentation/d/e/2PACX-1vSc7Q82-lwQ8fKgR5WcT7Y0r9kotcYiNuyYjHRlF-fdhf6lkIrF9B_2akvzL-ZQ6ZAyT1lxM9f0mPdx/pub?start=false&loop=false&delayms=3000
    github: https://github.com/RodolfoFerro/PythonBaseAPI
    img: python-base-api.png
    tags: [Flask, Python, API, scikit-learn]
  item7:
    title: flask-micro-template
    subtitle: A micro template built with Flask
    description: A micro template built with Flask and Bootstrap. Used for minimal testing in Glitch.
    link: https://flask-micro-template.glitch.me
    github: https://github.com/RodolfoFerro/flask-micro-template
    img: flask-micro-template.png
    tags: [Flask, Python, Bootstrap]
  item8:
    title: moltransform
    subtitle: Python package
    description: Molecular transformations for graphic displaying using Cartesian coordinates.
    link: https://pypi.org/project/moltransform/
    github: https://github.com/RodolfoFerro/moltransform
    img: moltransform.png
    tags: [Python, PyPI, Molecules, Rigid Transformations]
  item9:
    title: FitbitVersa-SimpleOmnitrix
    subtitle: Fitbit Versa Clockface
    description: My first clock face for Fitbit Versa, inspired in Ben 10's Omnitrix.
    link: https://gallery.fitbit.com/details/6c75fa41-8de0-41db-b851-f21f7447018b
    github: https://github.com/RodolfoFerro/FitbitVersa-SimpleOmnitrix
    img: simple-omnitrix.png
    tags: [TypeScript, Ben 10, Fitbit, Fitbit Versa]


# Certifications and awards section
awards:
  - 'Winner – #TFWorld TF 2.0 Challenge – TensorFlow at Devpost 2020'
  - Academy and Technology – Statal Youth Prize Guanajuato 2018
  - Quantum Computing 101 – IBM Q Certification Badge 2018
  - 1st. Place – HDI Challenge – Talent City Hackathon 2018
  - 1st. Place – SWITCH Hackathon 2017
  - 1st. Place – IBM Hackapalooza – Bluehack Hackathon 2017
  - 1st. Place – 12th. Creativity and Innovation Contest at the University of Guanajuato 2017
  - 1st. Place – Centro Fox National Hackathon 2017
  - 1st. Place – 6th. Creativity and Innovation Contest, DCEA-UG 2016
  - Silver Award – SynBio Giant Jamboree – iGEM  2016
  - 1st. Place – 4th. Creativity and Innovation Contest, DCNE-UG 2016
  - 1st. Place – Fintech – HackBajío Hackathon 2016
